### ISSUE TITLE
Multiple Entry Fields

### ISSUE THREAD

**Issue by matdave** [pqina/filepond-server-php#1]
Currently, it only allows for one entry field. We have a form that we want to have a file upload and a gallery upload. Is there a way to set multiple entry options?

**Comment by rikschennink** [comment]
It should accept multiple fields on form submit, I'll run some tests next week.

**Comment by rikschennink** [comment]
Just pushed a new version, you can now set an array of field names to the `ENTRY_FIELD` constant, please confirm this solves the issue.
