### ISSUE TITLE
Hi thanks for the api but issue with moving file from tmp to uploads

### ISSUE THREAD

**Issue by github-admin-bodwell** [pqina/filepond-server-php#3]
somehow they are successfully stored in tmp folder but when i submit they dont move to uploads.

Just wondering if you know the way to fix this issue

**Comment by rikschennink** [comment]
Do you get any errors, and does the problem also happen with the [filepond-php-boilerplate](https://github.com/pqina/filepond-boilerplate-php)?

**Comment by thierrymichel** [comment]
@rikschennink same here.
Just copied `.php` files into a `process` folder and used minimal `setOptions({ server: './process/'})`.
Everything seems fine (upload complete), files are stored in `tmp` but not moved to `uploads`…

Same results with the boilerplate:
![image](https://user-images.githubusercontent.com/806883/54759545-98d66d80-4bee-11e9-8966-b7d291f8c63c.png)

Thanks for your help!

**Comment by rikschennink** [comment]
I've just checked-out the [boilerplate](https://github.com/pqina/filepond-boilerplate-php) project and uploaded and submitted a file. Both actions work correctly.

Please check the server logs to see if there are any errors.

**Comment by thierrymichel** [comment]
@rikschennink ok, blame on me…

> …uploaded and __submitted__ a file. __Both actions__ …

I didn't get that I had to submit 😅
It works like a charm :+1:

**Comment by myerzman** [comment]
I'm having the same problem - goes just to tmp directory  - how do I submit ? I'm using react

**Comment by st-way** [comment]
You have to submit the form containing filepond inputs to submit.php, using a classic button or an ajax request

**Comment by myerzman** [comment]
thanks!
