### ISSUE TITLE
Potential security issue (code execution on server)

### ISSUE THREAD

**Issue by dtugend** [pqina/filepond-server-php#6]
@rikschennink Please check your Twitter DM, there might be a security issue allowing code execution on the server - not 100% sure, but please take a look at it!

**Comment by rikschennink** [comment]
looking into it

**Comment by rikschennink** [comment]
Thanks, it's fixed in 2.0.1
https://github.com/pqina/filepond-server-php/releases/tag/2.0.1

**Comment by dtugend** [comment]
Thank you very much for fixing that and something related I didn't even report.
