### ISSUE TITLE
Example PHP Server - does not move metadata file

### ISSUE THREAD

**Issue by mbwhite** [pqina/filepond-server-php#7]
Using the latest codebases for Filepond, and the example PHP server, I've noticed that the metadata file remains in the 'transfer' directory, but the image is moved to the 'uploads' directory.

As the filename of the metadata file appear to be fixed, is this intentional behaviour?

Thanks!

**Comment by rikschennink** [comment]
it's an example implementation, you'll probably want to do something with the metadata as well, if not, the file can be removed as well.

**Comment by mbwhite** [comment]
thanks.. I suspected that was the case but wanted to verify that is wasn't a misconfiguration.
